
# Прогноз виручки за 7 днів для оцінки маркетингу.
Розроблений прогноз має допомагати маркетологам якомога раніше і точніше приймати рішення

In [33]:
# Libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.pyplot import ylabel

In [34]:
# Зчитуємо дані та оглядаємо
data1 = pd.read_csv("../../data/task_2_users_actions.csv")
data2 = pd.read_csv("../../data/task_2_users_params.csv")

------------------
# Поверхневий EDA

In [35]:

print("task_2_users_actions.csv: ")
print("Shape: ", data1.shape)
display(data1.head(3))

print("task_2_users_params.csv: ")
print("Shape: ", data2.shape)
display(data2.head(3))

task_2_users_actions.csv:
Shape:  (6456848, 8)

,id_user,timestamp_interval_start,timestamp_interval_end,sum_payments,cnt_payments,sum_credits_spend,cnt_returns,cnt_visit_other_users
0,2672114,2024-08-20 07:07:14.493905+00:00,2024-08-20 13:07:14.493905+00:00,0.0,0,0,0,2
1,2672114,2024-08-20 13:07:14.493905+00:00,2024-08-20 19:07:14.493905+00:00,0.0,0,0,0,0
2,2672114,2024-08-20 19:07:14.493905+00:00,2024-08-21 01:07:14.493905+00:00,0.0,0,0,0,0

task_2_users_params.csv:
Shape:  (1905428, 13)

,id_user,timestamp_reg,age,traffic_type_id,traffic_group_id,gender,country,device_browser,device_brand,device_model,device_platform,device_os,revenue_7d
0,1,2024-09-28 01:32:16.011076+00:00,53,1,1,male,CA,Mobile Silk,Amazon,Fire HD 10 (2021),tablet,Android,0.0
1,1,2024-09-28 01:32:16.011076+00:00,53,1,1,male,CA,Mobile Silk,Amazon,Fire HD 10 (2021),tablet,Android,0.0
2,13,2024-10-18 17:05:48.437175+00:00,53,1,7,male,US,Mobile Silk,Amazon,Fire HD 8 (2022),tablet,Android,0.0

In [36]:
# Детальна інформація по датасетам
data1.info(memory_usage='deep')
data2.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 6456848 entries, 0 to 6456847
Data columns (total 8 columns):
 #   Column                    Dtype
---  ------                    -----
 0   id_user                   int64
 1   timestamp_interval_start  str
 2   timestamp_interval_end    str
 3   sum_payments              float64
 4   cnt_payments              int64
 5   sum_credits_spend         int64
 6   cnt_returns               int64
 7   cnt_visit_other_users     int64
dtypes: float64(1), int64(5), str(2)
memory usage: 1.3 GB
<class 'pandas.DataFrame'>
RangeIndex: 1905428 entries, 0 to 1905427
Data columns (total 13 columns):
 #   Column            Dtype
---  ------            -----
 0   id_user           int64
 1   timestamp_reg     str
 2   age               int64
 3   traffic_type_id   int64
 4   traffic_group_id  int64
 5   gender            str
 6   country           str
 7   device_browser    str
 8   device_brand      str
 9   device_model      str
 10  device_platform   str
 11  device_os         str
 12  revenue_7d        float64
dtypes: float64(1), int64(4), str(8)
memory usage: 915.6 MB

In [37]:
df_users_actions = data1.copy()
df_users_params = data2.copy()

In [38]:
miss_data_in_params = df_users_params.isnull().sum()
miss_data_in_actions = df_users_actions.isnull().sum()

print("Miss data:\n",miss_data_in_params)
print("Miss data:\n",miss_data_in_actions)

print("Params shape:", df_users_params.shape)
print("Actions shape:", df_users_actions.shape)

print("Унікальних юзерів в params:", df_users_params['id_user'].nunique())
print("Унікальних юзерів в actions:", df_users_actions['id_user'].nunique())

Miss data:
 id_user                  0
timestamp_reg            0
age                      0
traffic_type_id          0
traffic_group_id         0
gender                   0
country               4345
device_browser        6861
device_brand        283445
device_model        181811
device_platform       6893
device_os             6861
revenue_7d               0
dtype: int64
Miss data:
 id_user                     0
timestamp_interval_start    0
timestamp_interval_end      0
sum_payments                0
cnt_payments                0
sum_credits_spend           0
cnt_returns                 0
cnt_visit_other_users       0
dtype: int64
Params shape: (1905428, 13)
Actions shape: (6456848, 8)
Унікальних юзерів в params: 1614200
Унікальних юзерів в actions: 1614200

In [39]:
df_users_params[['age', 'revenue_7d']].describe()
df_users_actions[['sum_payments', 'cnt_payments', 'sum_credits_spend']].describe()

       sum_payments  cnt_payments  sum_credits_spend
count  6.456848e+06  6.456848e+06       6.456848e+06
mean   1.032068e-01  7.044459e-03       3.716503e+00
std    3.940898e+00  1.431226e-01       2.475382e+01
min    0.000000e+00  0.000000e+00       0.000000e+00
25%    0.000000e+00  0.000000e+00       0.000000e+00
50%    0.000000e+00  0.000000e+00       0.000000e+00
75%    0.000000e+00  0.000000e+00       0.000000e+00
max    2.446800e+03  5.500000e+01       1.573000e+04

In [40]:
print(df_users_params['gender'].value_counts())
print(df_users_params['device_platform'].value_counts())

gender
male      1667485
female     237943
Name: count, dtype: int64
device_platform
mobile     1713627
desktop     145571
tablet       38154
tv             850
console        332
car              1
Name: count, dtype: int64