In [3]:
# Libraries
import pandas as pd

In [9]:
data1 = pd.read_csv("../data/task_1.csv")
data1.head()

       id  id_user action           timestamp_action
0  674314        1   open  2024-11-20 16:25:01+00:00
1  678548        1  close  2024-11-20 17:08:32+00:00
2  682768        1   open  2024-11-20 17:50:14+00:00
3  697329        1  close  2024-11-20 20:07:49+00:00
4  775747        1   open  2024-11-21 09:50:55+00:00

In [10]:
data2 = pd.read_csv("../data/task_2_users_actions.csv")
data2.head()

,id_user,timestamp_interval_start,timestamp_interval_end,sum_payments,cnt_payments,sum_credits_spend,cnt_returns,cnt_visit_other_users
0,2672114,2024-08-20 07:07:14.493905+00:00,2024-08-20 13:07:14.493905+00:00,0.0,0,0,0,2
1,2672114,2024-08-20 13:07:14.493905+00:00,2024-08-20 19:07:14.493905+00:00,0.0,0,0,0,0
2,2672114,2024-08-20 19:07:14.493905+00:00,2024-08-21 01:07:14.493905+00:00,0.0,0,0,0,0
3,2672114,2024-08-21 01:07:14.493905+00:00,2024-08-21 07:07:14.493905+00:00,0.0,0,0,0,0
4,4314012,2024-08-20 07:07:25.610218+00:00,2024-08-20 13:07:25.610218+00:00,0.0,0,0,0,4

In [11]:
data3 = pd.read_csv("../data/task_2_users_params.csv")
data3.head()

,id_user,timestamp_reg,age,traffic_type_id,traffic_group_id,gender,country,device_browser,device_brand,device_model,device_platform,device_os,revenue_7d
0,1,2024-09-28 01:32:16.011076+00:00,53,1,1,male,CA,Mobile Silk,Amazon,Fire HD 10 (2021),tablet,Android,0.0
1,1,2024-09-28 01:32:16.011076+00:00,53,1,1,male,CA,Mobile Silk,Amazon,Fire HD 10 (2021),tablet,Android,0.0
2,13,2024-10-18 17:05:48.437175+00:00,53,1,7,male,US,Mobile Silk,Amazon,Fire HD 8 (2022),tablet,Android,0.0
3,15,2024-10-18 11:52:55.519693+00:00,23,1,5,male,NL,Opera Mobile,Infinix,S5,mobile,Android,0.0
4,16,2024-10-18 00:01:54.316289+00:00,23,1,5,male,US,Snapchat,Motorola,Moto g play,mobile,Android,0.0